#ifndef LINK_ALL_SYMBOLS_H_
#define LINK_ALL_SYMBOLS_H_
// Generated by GenLinkerSymbols.py. Do not modify! 

#pragma comment(linker, "/include:?Download@@YAHXZ")
#pragma comment(linker, "/include:??_C@_08EMEDHABH@Dog?5run?4?$AA@")
#pragma comment(linker, "/include:??_C@_0M@KEAKLOKJ@Turtle?5run?4?$AA@")
#pragma comment(linker, "/include:?Run@Dog@@QAEXXZ")
#pragma comment(linker, "/include:?Foo@@YAHXZ")
#pragma comment(linker, "/include:??4Turtle@@QAEAAV0@ABV0@@Z")
#pragma comment(linker, "/include:?Run@Turtle@@QAEXXZ")
#pragma comment(linker, "/include:?Run@Fish@@QAEXXZ")
#pragma comment(linker, "/include:?FishRun@@YAXXZ")

#endif // LINK_ALL_SYMBOLS_H_
